apiVersion: v1
kind: Service
metadata:
  name: aion-service
  namespace: aion-system
spec:
  selector:
    app: aion-runtime
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
